// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Eventos.AcessoADados;
using System;

namespace Eventos.AcessoADados.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    partial class BancoDeDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Eventos.AcessoADados.Modelos.Evento", b =>
            {
                b.Property<int>("IdEvento")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Nome")
                    .IsRequired();

                b.Property<string>("Data")
                    .IsRequired();

                b.Property<string>("Local")
                    .IsRequired();

                b.Property<int>("HoraInicio")
                    .IsRequired();

                b.Property<int>("HoraFinal")
                    .IsRequired();

                b.Property<bool>("OpenBar");

                b.Property<int>("QuantidadeDeAmbientes");

                b.Property<string>("FaixaEtaria");

                b.HasKey("IdEvento");

                b.ToTable("Eventos");
            });
#pragma warning restore 612, 618
        }
    }
}
